apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-kustomize-prod

namePrefix: prod-


resources:
- ../../base

patches:
- path: replica-patch.yaml
- path: configmap-patch.yaml
labels:
- includeSelectors: true
  pairs:
    environment: prod
