apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-base


resources:
- deployment.yaml
- service.yaml
- configmap.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: argocd-lab
